# Generated by Django 4.2.2 on 2023-12-04 19:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.ManyToManyField(blank=True, to="review.note"),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_imported_commit",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
