# Generated by Django 4.2.2 on 2023-09-02 15:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="avatar",
            field=models.ImageField(
                default="favicon-16x16.png",
                help_text="the profile image",
                null=True,
                upload_to="uploads/",
            ),
        ),
        migrations.AlterField(
            model_name="purl",
            name="avatar",
            field=models.ImageField(
                default="favicon-16x16.png",
                help_text="the profile image",
                null=True,
                upload_to="uploads/",
            ),
        ),
    ]
