# Generated by Django 4.2.2 on 2023-10-27 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purl",
            name="avatar",
        ),
    ]
