services:
  vulnerablecode:
    volumes:
      - .\vulnerablecode-config:/etc/vulnerablecode/

  vulnerablecode_scheduler:
    volumes:
      - .\vulnerablecode-config:/etc/vulnerablecode/

  vulnerablecode_rqworker:
    volumes:
      - .\vulnerablecode-config:/etc/vulnerablecode/

  vulnerablecode_rqworker_high:
    volumes:
      - .\vulnerablecode-config:/etc/vulnerablecode/
