# Generated by Django 2.2.4 on 2019-11-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text='A short code to identify the type of this package. For example: gem for a Rubygem, docker for a container, pypi for a Python Wheel or Egg, maven for a Maven Jar, deb for a Debian package, etc.', max_length=16, null=True)),
                ('namespace', models.CharField(blank=True, help_text='Package name prefix, such as Maven groupid, Docker image owner, GitHub user or organization, etc.', max_length=255, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the package.', max_length=100, null=True)),
                ('version', models.CharField(blank=True, help_text='Version of the package.', max_length=50, null=True)),
                ('qualifiers', models.CharField(blank=True, help_text='Extra qualifying data for a package such as the name of an OS, architecture, distro, etc.', max_length=1024, null=True)),
                ('subpath', models.CharField(blank=True, help_text='Extra subpath within a package, relative to the package root.', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(help_text='CVE ID', max_length=50, null=True, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Summary of the vulnerability')),
                ('cvss', models.FloatField(help_text='CVSS Score', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolvedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Package')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vulnerability')),
            ],
        ),
        migrations.CreateModel(
            name='PackageReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(blank=True, help_text='Repository URL eg:http://central.maven.org', max_length=100)),
                ('platform', models.CharField(blank=True, help_text='Platform eg:maven', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Package reference name eg:org.apache.commons.io', max_length=50)),
                ('version', models.CharField(blank=True, help_text='Reference version', max_length=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='vulnerabilities',
            field=models.ManyToManyField(through='core.ImpactedPackage', to='core.Vulnerability'),
        ),
        migrations.AddField(
            model_name='impactedpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Package'),
        ),
        migrations.AddField(
            model_name='impactedpackage',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vulnerability'),
        ),
        migrations.CreateModel(
            name='VulnerabilityReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='Source(s) name eg:NVD', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID, eg:DSA-4465-1', max_length=50)),
                ('url', models.URLField(blank=True, help_text='URL of Vulnerability data', max_length=1024)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Vulnerability')),
            ],
            options={
                'unique_together': {('vulnerability', 'source', 'reference_id', 'url')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='impactedpackage',
            unique_together={('vulnerability', 'package')},
        ),
    ]
