# Generated by Django 5.2.11 on 2026-07-23 21:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="PackageInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("package", models.CharField(max_length=50)),
                ("total_packages", models.IntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_insights",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageCWEInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cwe_id", models.CharField(max_length=50)),
                ("count", models.IntegerField()),
                (
                    "package_insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cwes",
                        to="insights.packageinsight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageNameInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("count", models.IntegerField()),
                (
                    "package_insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="insights.packageinsight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeverityInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "buckets",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        help_text="Scores mapped to buckets 0-10 (e.g. 0.0-0.9 -> index 0)",
                        size=10,
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="severity_insight",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImporterInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("importer", models.CharField(max_length=100)),
                ("total_advisories", models.IntegerField(default=0)),
                ("advisories_with_packages", models.IntegerField(default=0)),
                ("advisories_with_ghost_packages", models.IntegerField(default=0)),
                ("advisories_with_kev", models.IntegerField(default=0)),
                ("advisories_with_metasploit", models.IntegerField(default=0)),
                ("advisories_with_exploitdb", models.IntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importer_insights",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "importer"), name="unique_snapshot_importer"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="packageinsight",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "package"), name="unique_snapshot_package"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagecweinsight",
            constraint=models.UniqueConstraint(
                fields=("package_insight", "cwe_id"), name="unique_package_cwe"
            ),
        ),
        migrations.AddConstraint(
            model_name="packagenameinsight",
            constraint=models.UniqueConstraint(
                fields=("package_insight", "name"), name="unique_package_name"
            ),
        ),
    ]
