# Generated by Django 5.2.11 on 2026-08-08 22:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverviewInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("total_advisories", models.IntegerField(default=0)),
                ("total_packages", models.IntegerField(default=0)),
                ("total_data_sources", models.IntegerField(default=0)),
                (
                    "last_30days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverviewCoverageInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_name", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
                (
                    "overview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_insights",
                        to="insights.overviewinsight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverviewYearlyInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField()),
                ("count", models.IntegerField()),
                (
                    "overview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_insights",
                        to="insights.overviewinsight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataQualityIssueByDatasourceInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issue_type", models.CharField(max_length=50)),
                ("datasource_id", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_quality_issue_types",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "issue_type", "datasource_id"),
                        name="unique_snapshot_issue_type_datasource",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataQualityToDosResolutionInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("datasource_id", models.CharField(max_length=100)),
                (
                    "month",
                    models.DateField(help_text="The first day of the month for this data point."),
                ),
                ("open_count", models.IntegerField(default=0)),
                ("resolved_count", models.IntegerField(default=0)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_quality_todos_resolutions",
                        to="insights.dailysnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "datasource_id", "month"),
                        name="unique_snapshot_todos_resolution_datasource_month",
                    )
                ],
            },
        ),
    ]
