name: Detect Non-Existent CVEs

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 2 * * 0'  # Run weekly on Sunday at 2:00 AM UTC

jobs:
  detect-nonexistent-cves:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run pipeline
        run: |
          python manage.py improve detect_nonexistent_cves