name: generate Documentation

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.13 ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          cache: true

      - shell: bash
        run: |
          uv sync

      - name: Check Sphinx Documentation build minimally
        working-directory: docs
        run: |
          hatch run check_build

      - name: Check for documentation style errors
        working-directory: docs
        run: |
            hatch run docs:check_style
