name: run tests

on: [ push, pull_request ]

env:
  DB_NAME: vulnerablecode
  DB_USER: vulnerablecode
  DB_PASSWORD: vulnerablecode

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.13" ]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          cache: true

      - shell: bash
        run: |
          uv sync

      - name: Run tests
        run: |
          pytest -vvs -m "not webtest" --disable-warnings
        env:
          GH_TOKEN: 1
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          VULNERABLECODE_DB_NAME: ${{ env.DB_NAME }}
          VULNERABLECODE_DB_USER: ${{ env.DB_USER }}
          VULNERABLECODE_DB_PASSWORD: ${{ env.DB_PASSWORD }}
