on:
  workflow_dispatch: # allow manual execution
  push:
  pull_request:
  schedule:
    # run on the 3rd each month at 10:00am
    - cron: '0 10 3 * *'

jobs:
  nix-check-and-import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v11
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.09.tar.gz
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: run checks & test import
        run: |
          cd etc/nix
          nix --print-build-logs flake check
          ./test-import-using-nix.sh alpine
