on:
  workflow_dispatch: # allow manual execution
  schedule:
    # run on every 9 o'clock
    - cron: '0 9 * * *'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python 3.8.11
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.8.11

      - name: Install dependencies
        run: |
          sudo apt-get install -y postgresql python3-dev libpq-dev build-essential
          make dev envfile

      - name: Setup database
        run: |
          sudo systemctl start postgresql
          make postgres
    
      - name: Run upstream tests
        run: make webtest
        env:
          GH_TOKEN: 1 
