# Generated by Django 4.0.1 on 2022-02-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Importer",
        ),
    ]
