# Generated by Django 3.0.7 on 2021-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagerelatedvulnerability',
            options={'verbose_name_plural': 'Package related vulnerabilities'},
        ),
    ]
