# Generated by Django 3.0.3 on 2020-04-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryHashes',
            fields=[
                ('hash', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'verbose_name_plural': 'Vulnerabilities'},
        ),
    ]
