# Generated by Django 3.0.13 on 2021-04-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagerelatedvulnerability",
            name="patched_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patched_package",
                to="vulnerabilities.Package",
            ),
        ),
        migrations.AlterField(
            model_name="packagerelatedvulnerability",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vulnerable_package",
                to="vulnerabilities.Package",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vulnerability_id",
            field=models.CharField(
                help_text="Unique identifier for a vulnerability: this is either a published CVE id (as in CVE-2020-7965) if it exists. Otherwise this is a VulnerableCode-assigned VULCOID (as in VULCOID-20210222-1315-16461541). When a vulnerability CVE is assigned later we replace this with the CVE and keep the 'old' VULCOID in the 'old_vulnerability_id' field to support redirection to the CVE id.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityseverity",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("cvssv2", "CVSSv2 Base Score"),
                    ("cvssv2_vector", "CVSSv2 Vector"),
                    ("cvssv3", "CVSSv3 Base Score"),
                    ("cvssv3_vector", "CVSSv3 Vector"),
                    ("cvssv3.1", "CVSSv3.1 Base Score"),
                    ("cvssv3.1_vector", "CVSSv3.1 Vector"),
                    ("rhbs", "RedHat Bugzilla severity"),
                    ("rhas", "RedHat Aggregate severity"),
                    ("avgs", "Archlinux Vulnerability Group Severity"),
                    ("cvssv3.1_qr", "CVSSv3.1 Qualitative Severity Rating"),
                    ("generic_textual", "Generic textual severity rating"),
                ],
                help_text="identifier for the scoring system used. Available choices are: cvssv2 is vulnerability_id for CVSSv2 Base Score system, cvssv2_vector is vulnerability_id for CVSSv2 Vector system, cvssv3 is vulnerability_id for CVSSv3 Base Score system, cvssv3_vector is vulnerability_id for CVSSv3 Vector system, cvssv3.1 is vulnerability_id for CVSSv3.1 Base Score system, cvssv3.1_vector is vulnerability_id for CVSSv3.1 Vector system, rhbs is vulnerability_id for RedHat Bugzilla severity system, rhas is vulnerability_id for RedHat Aggregate severity system, avgs is vulnerability_id for Archlinux Vulnerability Group Severity system, cvssv3.1_qr is vulnerability_id for CVSSv3.1 Qualitative Severity Rating system, generic_textual is vulnerability_id for Generic textual severity rating system ",
                max_length=50,
            ),
        ),
    ]
