# Generated by Django 2.2 on 2019-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_package_vulnerabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='cvss',
            field=models.FloatField(help_text='CVSS Score', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='summary',
            field=models.CharField(blank=True, help_text='Summary of the vulnerability', max_length=100),
        ),
    ]
