# Generated by Django 3.0.14 on 2021-04-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0002_auto_20210420_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='last_import',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_import_run', to='vulnerabilities.ImportRun'),
        ),
    ]
