# Generated by Django 4.0.2 on 2022-03-29 09:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0003_alter_advisory_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="unique_content_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
