# Generated by Django 3.0.7 on 2020-11-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20201127_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vulnerabilityseverity',
            unique_together={('vulnerability', 'reference', 'system')},
        ),
    ]
