# Generated by Django 2.2 on 2019-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20190406_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of the vulnerability'),
        ),
    ]
