# Generated by Django 3.0.14 on 2021-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0003_auto_20210420_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='last_run',
            field=models.DateTimeField(help_text='UTC Timestamp of the last run', null=True),
        ),
    ]
