# Generated by Django 3.0.7 on 2020-12-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_auto_20201129_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityseverity',
            name='scoring_system_identifier',
            field=models.CharField(default='', help_text='Example: cvssv2', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vulnerabilityseverity',
            unique_together={('vulnerability', 'reference', 'scoring_system_identifier')},
        ),
        migrations.RemoveField(
            model_name='vulnerabilityseverity',
            name='system',
        ),
    ]
