# Generated by Django 4.0.2 on 2022-03-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0005_auto_20220329_0938"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together={("aliases", "unique_content_id", "date_published")},
        ),
    ]
