# Generated by Django 3.0.7 on 2021-01-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0005_auto_20201218_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityseverity',
            name='scoring_system',
            field=models.CharField(choices=[('cvssv2', 'CVSSv2'), ('cvssv3', 'CVSSv3'), ('rhbs', 'RedHat Bugzilla severity'), ('rhas', 'RedHat Aggregate severity'), ('rh_cvssv3', 'RedHat CVSSv3')], default='', help_text='Scoring system used for this score', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vulnerabilityseverity',
            unique_together={('vulnerability', 'reference', 'scoring_system')},
        ),
        migrations.RemoveField(
            model_name='vulnerabilityseverity',
            name='scoring_system_identifier',
        ),
    ]
