# Generated by Django 2.2.4 on 2019-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0005_auto_20190411_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='platform',
        ),
        migrations.AddField(
            model_name='package',
            name='namespace',
            field=models.CharField(blank=True, help_text='Package name prefix, such as Maven groupid, Docker image owner, GitHub user or organization, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='qualifiers',
            field=models.CharField(blank=True, help_text='Extra qualifying data for a package such as the name of an OS, architecture, distro, etc.', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='subpath',
            field=models.CharField(blank=True, help_text='Extra subpath within a package, relative to the package root.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(blank=True, help_text='A short code to identify the type of this package. For example: gem for a Rubygem, docker for a container, pypi for a Python Wheel or Egg, maven for a Maven Jar, deb for a Debian package, etc.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the package.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(blank=True, help_text='Version of the package.', max_length=50, null=True),
        ),
    ]
