# Generated by Django 4.0.7 on 2022-09-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0026_alter_package_purl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory',
            options={'ordering': ['aliases', 'date_published', 'unique_content_id']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['purl']},
        ),
        migrations.AlterModelOptions(
            name='packagerelatedvulnerability',
            options={'ordering': ['package', 'vulnerability'], 'verbose_name_plural': 'PackageRelatedVulnerabilities'},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['vulnerability_id'], 'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilityrelatedreference',
            options={'ordering': ['vulnerability', 'reference']},
        ),
        migrations.AlterModelOptions(
            name='vulnerabilityseverity',
            options={'ordering': ['reference', 'scoring_system', 'value']},
        ),
    ]
