# Generated by Django 4.0.7 on 2022-10-28 10:04

from django.db import migrations
import vulnerabilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vulnerabilities', '0028_alter_packagerelatedvulnerability_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', vulnerabilities.models.ApiUserManager()),
            ],
        ),
    ]
