# Generated by Django 4.0.7 on 2022-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0033_alter_vulnerabilityseverity_scoring_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_url',
            field=models.CharField(blank=True, db_index=True, help_text='The Package URL for this package.', max_length=255),
        ),
    ]
