# Generated by Django 4.0.7 on 2022-11-25 12:57

from django.db import migrations
from packageurl import PackageURL

class Migration(migrations.Migration):

    def save_package(apps, schema_editor):
        Package = apps.get_model("vulnerabilities", "Package")
        for package in Package.objects.all():
            purl = PackageURL(
                type=package.type,
                namespace=package.namespace,
                name=package.name,
                version=package.version,
                qualifiers=package.qualifiers,
                subpath=package.subpath,
            )
            package.package = str(purl)
            package.save()

    dependencies = [
        ('vulnerabilities', '0034_package_package'),
    ]

    operations = [
        migrations.RunPython(save_package, reverse_code=migrations.RunPython.noop),
    ]
