# Generated by Django 4.1.7 on 2023-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0039_alter_vulnerabilityseverity_scoring_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisory",
            name="date_improved",
        ),
        migrations.AddField(
            model_name="advisory",
            name="date_imported",
            field=models.DateTimeField(
                blank=True, help_text="UTC Date on which the advisory was imported", null=True
            ),
        ),
    ]
