# Generated by Django 4.1.7 on 2023-07-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0039_alter_vulnerabilityseverity_scoring_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hash",
                    models.CharField(blank=True, help_text="Hash of the commit", max_length=1024),
                ),
                (
                    "chain_urls",
                    models.JSONField(
                        blank=True, default=list, help_text="List of URLS used to reach the commit"
                    ),
                ),
                (
                    "reference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vulnerabilities.vulnerabilityreference",
                    ),
                ),
            ],
            options={
                "ordering": ["reference_id"],
            },
        ),
    ]
