# Generated by Django 4.1.7 on 2023-09-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0039_alter_vulnerabilityseverity_scoring_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Improver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("improver_qualified_name", models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name="advisory",
            name="date_improved",
        ),
        migrations.CreateModel(
            name="ImproverRelatedAdvisory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_improved",
                    models.DateTimeField(
                        help_text="Date on which the advisory was improved by an improver",
                        null=True,
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vulnerabilities.advisory"
                    ),
                ),
                (
                    "improver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vulnerabilities.improver"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="improver",
            name="advisories",
            field=models.ManyToManyField(
                through="vulnerabilities.ImproverRelatedAdvisory", to="vulnerabilities.advisory"
            ),
        ),
        migrations.AddField(
            model_name="advisory",
            name="improvers",
            field=models.ManyToManyField(
                through="vulnerabilities.ImproverRelatedAdvisory", to="vulnerabilities.improver"
            ),
        ),
    ]
