# Generated by Django 4.1.7 on 2023-09-01 15:43

from django.db import migrations
from vulnerabilities.improver import Improver
from vulnerabilities.improvers import IMPROVERS_REGISTRY
from vulnerabilities.improvers.default import AdvisoryBasedDefaultImprover

class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0040_improver_remove_advisory_date_improved_and_more"),
    ]

    def register_improvers(apps, _):
        Improver = apps.get_model("vulnerabilities", "Improver")
        for qual_name, _ in IMPROVERS_REGISTRY.items():
            Improver.objects.create(
                improver_qualified_name = qual_name
            )
        Improver.objects.create(
            improver_qualified_name = AdvisoryBasedDefaultImprover.qualified_name
        )
    
    dependencies = [
        ("vulnerabilities", "0040_improver_remove_advisory_date_improved_and_more"),
    ]

    operations = [
        migrations.RunPython(register_improvers,reverse_code=migrations.RunPython.noop)
    ]
