# Generated by Django 4.0.7 on 2023-03-07 10:48

import datetime

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0040_advisory_date_created_advisory_date_modified_and_more"),
    ]

    def initialize_models_with_current_datetime(apps, schema_editor):
        Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
        Advisory = apps.get_model("vulnerabilities", "Advisory")
        VulnerabilityReference = apps.get_model("vulnerabilities", "VulnerabilityReference")
        Package = apps.get_model("vulnerabilities", "Package")
        VulnerabilitySeverity = apps.get_model("vulnerabilities", "VulnerabilitySeverity")
        Alias = apps.get_model("vulnerabilities", "Alias")
        PackageRelatedVulnerability = apps.get_model(
            "vulnerabilities", "PackageRelatedVulnerability"
        )
        VulnerabilityRelatedReference = apps.get_model(
            "vulnerabilities", "VulnerabilityRelatedReference"
        )
        Weakness = apps.get_model("vulnerabilities", "Weakness")
        models = [
            Vulnerability,
            Advisory,
            VulnerabilityReference,
            Package,
            VulnerabilitySeverity,
            Alias,
            PackageRelatedVulnerability,
            VulnerabilityRelatedReference,
            Weakness,
        ]
        # take date as datetime now
        date = datetime.datetime.now()
        for model in models:
            updatables = []
            for obj in model.objects.all():
                obj.date_created = date
                obj.date_modified = date
                updatables.append(obj)
            # update in bulk, 500 at a time
            updated = model.objects.bulk_update(
                objs=updatables,
                fields=["date_created", "date_modified"],
                batch_size=500,
            )
            print(f"Migrated {updated} objects in {model} with current datetime")

    operations = [
        migrations.RunPython(initialize_models_with_current_datetime, migrations.RunPython.noop),
    ]
