# Generated by Django 4.1.7 on 2023-10-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0041_advisory_url_vulnerabilitychangelog_packagechangelog"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together={("aliases", "unique_content_id", "date_published", "url")},
        ),
    ]
