# Generated by Django 4.1.13 on 2023-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0042_advisory_status_vulnerability_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="vulnerabilities",
            field=models.ManyToManyField(
                related_name="advisories", to="vulnerabilities.vulnerability"
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="date_published",
            field=models.DateTimeField(
                blank=True, help_text="UTC Date of publication of the vulnerability", null=True
            ),
        ),
    ]
