# Generated by Django 4.1.7 on 2023-09-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0042_alter_packagechangelog_vulnerablecode_version_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together={("aliases", "unique_content_id", "date_published", "url")},
        ),
    ]
