# Generated by Django 4.1.13 on 2023-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0044_alter_packagechangelog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagechangelog",
            name="software_version",
            field=models.CharField(
                default="33.6.6",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitychangelog",
            name="software_version",
            field=models.CharField(
                default="33.6.6",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
    ]
