# Generated by Django 4.1.13 on 2023-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0045_remove_duplicated_purls_with_same_qualifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="qualifiers_temp",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
