# Generated by Django 4.1.7 on 2023-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0048_alter_package_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={
                ("type", "namespace", "name", "version", "subpath", "qualifiers_temp")
            },
        ),
        migrations.AlterField(
            model_name="package",
            name="qualifiers",
            field=models.CharField(
                blank=True,
                help_text="Extra qualifying data for a package such as the name of an OS, architecture, distro, etc.",
                max_length=1024,
            ),
        ),
    ]
