# Generated by Django 4.1.7 on 2023-12-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0048_copy_qualifiers_temp_to_qualifiers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("type", "namespace", "name", "version", "qualifiers", "qualifiers_temp", "subpath")},
        ),
    ]
