# Generated by Django 4.1.7 on 2023-12-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0051_alter_package_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("type", "namespace", "name", "version", "qualifiers", "subpath")},
        ),
        migrations.RemoveField(
            model_name="package",
            name="qualifiers_temp",
        ),
    ]
