# Generated by Django 4.1.13 on 2024-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0052_remove_duped_purls_with_namespace_name_mixed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagechangelog",
            name="software_version",
            field=models.CharField(
                default="34.0.0rc1",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitychangelog",
            name="software_version",
            field=models.CharField(
                default="34.0.0rc1",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
    ]
