# Generated by Django 4.1.13 on 2024-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0055_remove_changelogs_with_same_data_different_software_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagechangelog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="vulnerabilitychangelog",
            options={},
        ),
        migrations.AlterField(
            model_name="packagechangelog",
            name="software_version",
            field=models.CharField(
                default="34.0.0rc3",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitychangelog",
            name="software_version",
            field=models.CharField(
                default="34.0.0rc3",
                help_text="Version of the software at the time of change",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packagechangelog",
            unique_together={
                (
                    "action_time",
                    "actor_name",
                    "action_type",
                    "source_url",
                    "related_vulnerability",
                    "package",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitychangelog",
            unique_together={
                ("action_time", "actor_name", "action_type", "source_url", "vulnerability")
            },
        ),
    ]
