# Generated by Django 4.1.13 on 2024-01-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0055_remove_changelogs_with_same_data_different_software_version"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="packagechangelog",
            unique_together={("action_time", "actor_name", "action_type", "source_url")},
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitychangelog",
            unique_together={("action_time", "actor_name", "action_type", "source_url")},
        ),
    ]
