# Generated by Django 4.1.13 on 2024-08-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0059_vulnerabilityseverity_published_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("malicious", "Malicious Package"),
                    ("ghost", "Ghost Package"),
                    ("yanked", "Yanked Package"),
                    ("valid", "Valid Package"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text="The status of the package, malicious, ghost, yanked, valid or unknown.",
                max_length=20,
            ),
        ),
    ]
