# Generated by Django 4.1.13 on 2024-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0060_alter_kev_known_ransomware_campaign_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="is_ghost",
            field=models.BooleanField(
                default=False,
                help_text="True if the package does not exist in the upstream package manager or its repository.",
            ),
        ),
    ]
