# Generated by Django 4.2.15 on 2024-10-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0071_auto_20241007_1044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="vulnerabilities",
        ),
        migrations.RemoveField(
            model_name="vulnerability",
            name="packages",
        ),
        migrations.AddField(
            model_name="package",
            name="affected_by_vulnerabilities",
            field=models.ManyToManyField(
                through="vulnerabilities.AffectedByPackageRelatedVulnerability",
                to="vulnerabilities.vulnerability",
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="affecting_packages",
            field=models.ManyToManyField(
                through="vulnerabilities.AffectedByPackageRelatedVulnerability",
                to="vulnerabilities.package",
            ),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="fixed_by_packages",
            field=models.ManyToManyField(
                related_name="fixing_vulnerabilities",
                through="vulnerabilities.FixingPackageRelatedVulnerability",
                to="vulnerabilities.package",
            ),
        ),
    ]
