# Generated by Django 4.2.16 on 2024-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0073_delete_packagerelatedvulnerability"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="risk",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Enter a risk score between 0.00 and 10.00, where higher values indicate greater vulnerability risk for the package.",
                max_digits=4,
                null=True,
            ),
        ),
    ]
