# Generated by Django 4.2.15 on 2024-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0074_vulnerability_fixed_by_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="affected_by_vulnerabilities",
            field=models.ManyToManyField(
                through="vulnerabilities.AffectedByPackageRelatedVulnerability",
                to="vulnerabilities.vulnerability",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="affecting_packages",
            field=models.ManyToManyField(
                through="vulnerabilities.AffectedByPackageRelatedVulnerability",
                to="vulnerabilities.package",
            ),
        ),
    ]
