# Generated by Django 4.2.16 on 2024-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0082_vulnerability_exploitability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagechangelog",
            name="software_version",
            field=models.CharField(
                help_text="Version of the software at the time of change", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitychangelog",
            name="software_version",
            field=models.CharField(
                help_text="Version of the software at the time of change", max_length=100
            ),
        ),
    ]
