# Generated by Django 4.2.16 on 2024-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0083_alter_packagechangelog_software_version_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="package",
            options={
                "ordering": [
                    "type",
                    "namespace",
                    "name",
                    "version_rank",
                    "version",
                    "qualifiers",
                    "subpath",
                ]
            },
        ),
        migrations.AddField(
            model_name="package",
            name="version_rank",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the version to support ordering by version. Rank zero means the rank has not been defined yet",
            ),
        ),
    ]
