# Generated by Django 4.2.16 on 2024-12-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0084_alter_package_options_package_version_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeFix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("commits", models.JSONField(blank=True, default=list)),
                ("pulls", models.JSONField(blank=True, default=list)),
                ("downloads", models.JSONField(blank=True, default=list)),
                ("patch", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("references", models.JSONField(blank=True, default=list)),
                ("status_reviewed", models.BooleanField(default=False)),
                ("base_commit", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_versions",
                    models.ManyToManyField(
                        blank=True, related_name="fixes", to="vulnerabilities.package"
                    ),
                ),
                (
                    "base_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_version_changes",
                        to="vulnerabilities.package",
                    ),
                ),
                (
                    "vulnerabilities",
                    models.ManyToManyField(
                        blank=True, related_name="codefixes", to="vulnerabilities.vulnerability"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
