# Generated by Django 4.2.16 on 2024-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0084_alter_package_options_package_version_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="version_rank",
            field=models.FloatField(
                default=0,
                help_text="Rank of the version to support ordering by version. Rank zero means the rank has not been defined yet",
            ),
        ),
    ]
