# Generated by Django 4.2.16 on 2024-12-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0085_alter_package_is_ghost_alter_package_version_rank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeFix",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "commits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of commit identifiers associated with the code change.",
                    ),
                ),
                (
                    "pulls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of pull request URLs associated with the code change.",
                    ),
                ),
                (
                    "downloads",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of download URLs for the patched code.",
                    ),
                ),
                (
                    "patch",
                    models.TextField(
                        blank=True,
                        help_text="The code change in patch format (e.g., git diff).",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or instructions about the code change.",
                        null=True,
                    ),
                ),
                (
                    "references",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="External references related to this code change.",
                    ),
                ),
                (
                    "status_reviewed",
                    models.BooleanField(
                        default=False, help_text="Indicates if the code change has been reviewed."
                    ),
                ),
                (
                    "base_commit",
                    models.CharField(
                        blank=True,
                        help_text="The commit ID representing the state of the code before applying the fix or change.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when the code change was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp indicating when the code change was last updated.",
                    ),
                ),
                (
                    "base_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The base version of the package to which this code change applies.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_version_codechanges",
                        to="vulnerabilities.package",
                    ),
                ),
                (
                    "package_vulnerabilities",
                    models.ManyToManyField(
                        help_text="The vulnerabilities fixed by this code change.",
                        related_name="code_fixes",
                        to="vulnerabilities.affectedbypackagerelatedvulnerability",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
