# Generated by Django 4.2.17 on 2025-01-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0087_update_alpine_advisory_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryTODO",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("MISSING_AFFECTED_PACKAGE", "Advisory is missing affected package"),
                            ("MISSING_FIXED_BY_PACKAGE", "Advisory is missing fixed-by package"),
                            (
                                "MISSING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisory is missing both affected and fixed-by packages",
                            ),
                            ("MISSING_SUMMARY", "Advisory is missing summary"),
                            (
                                "CONFLICTING_FIXED_BY_PACKAGES",
                                "Advisories have conflicting fixed-by packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_PACKAGES",
                                "Advisories have conflicting affected packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisories have conflicting affected and fixed-by packages",
                            ),
                            (
                                "CONFLICTING_SEVERITY_SCORES",
                                "Advisories have conflicting severity scores",
                            ),
                        ],
                        db_index=True,
                        help_text="Select the issue that needs to be addressed from the available options.",
                        max_length=50,
                    ),
                ),
                ("issue_detail", models.TextField(help_text="Additional details about the issue.")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this TODO was created.",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, help_text="This TODO is resolved or not."
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        help_text="Timestamp indicating when this TODO was resolved."
                    ),
                ),
                (
                    "resolution_detail",
                    models.TextField(help_text="Additional detail on how this TODO was resolved."),
                ),
                (
                    "advisories",
                    models.ManyToManyField(
                        help_text="Advisory/ies where this TODO is applicable.",
                        related_name="advisory_todos",
                        to="vulnerabilities.advisory",
                    ),
                ),
            ],
        ),
    ]
