# Generated by Django 4.2.17 on 2025-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0088_fix_alpine_purl_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="unique_content_id",
            field=models.CharField(
                blank=True,
                help_text="A 64 character unique identifier for the content of the advisory since we use sha256 as hex",
                max_length=64,
            ),
        ),
    ]
