# Generated by Django 4.2.16 on 2025-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0088_fix_alpine_purl_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="unique_content_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
