# Generated by Django 4.2.17 on 2025-03-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        ("vulnerabilities", "0088_fix_alpine_purl_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                ("expires", models.DateTimeField()),
            ],
            bases=("authtoken.token",),
        ),
    ]
