# Generated by Django 4.2.17 on 2025-03-01 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0088_fix_alpine_purl_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codefix",
            name="id",
        ),
        migrations.AddField(
            model_name="codefix",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this code fix",
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
