# Generated by Django 4.2.16 on 2025-02-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0089_alter_advisory_unique_content_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together={("aliases", "date_published", "url")},
        ),
    ]
