# Generated by Django 4.2.16 on 2025-02-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0090_alter_advisory_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together=set(),
        ),
    ]
