# Generated by Django 4.2.17 on 2025-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0090_migrate_advisory_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="advisory_id",
            field=models.CharField(
                blank=True,
                help_text="An advisory id, such as CVE-123-345 when available",
                max_length=100,
            ),
        ),
    ]
