# Generated by Django 4.2.17 on 2025-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0090_migrate_advisory_aliases"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="advisory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="unique_content_id",
            field=models.CharField(
                help_text="A 64 character unique identifier for the content of the advisory since we use sha256 as hex",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="url",
            field=models.URLField(help_text="Link to the advisory on the upstream website"),
        ),
    ]
