# Generated by Django 4.2.20 on 2025-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0091_alter_advisory_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="An alias is a unique vulnerability identifier in some database, such as CVE-2020-2233",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL to the vulnerability reference", max_length=1024, unique=True
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("advisory", "Advisory"),
                            ("exploit", "Exploit"),
                            ("mailing_list", "Mailing List"),
                            ("bug", "Bug"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="An optional reference ID, such as DSA-4465-1 when available",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["reference_id", "url", "reference_type"],
            },
        ),
        migrations.CreateModel(
            name="AdvisorySeverity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="URL to the vulnerability severity",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "scoring_system",
                    models.CharField(
                        choices=[
                            ("cvssv2", "CVSSv2 Base Score"),
                            ("cvssv3", "CVSSv3 Base Score"),
                            ("cvssv3.1", "CVSSv3.1 Base Score"),
                            ("cvssv4", "CVSSv4 Base Score"),
                            ("rhbs", "RedHat Bugzilla severity"),
                            ("rhas", "RedHat Aggregate severity"),
                            ("archlinux", "Archlinux Vulnerability Group Severity"),
                            ("cvssv3.1_qr", "CVSSv3.1 Qualitative Severity Rating"),
                            ("generic_textual", "Generic textual severity rating"),
                            ("apache_httpd", "Apache Httpd Severity"),
                            ("apache_tomcat", "Apache Tomcat Severity"),
                            ("epss", "Exploit Prediction Scoring System"),
                            ("ssvc", "Stakeholder-Specific Vulnerability Categorization"),
                        ],
                        help_text="Identifier for the scoring system used. Available choices are: cvssv2: CVSSv2 Base Score,\ncvssv3: CVSSv3 Base Score,\ncvssv3.1: CVSSv3.1 Base Score,\ncvssv4: CVSSv4 Base Score,\nrhbs: RedHat Bugzilla severity,\nrhas: RedHat Aggregate severity,\narchlinux: Archlinux Vulnerability Group Severity,\ncvssv3.1_qr: CVSSv3.1 Qualitative Severity Rating,\ngeneric_textual: Generic textual severity rating,\napache_httpd: Apache Httpd Severity,\napache_tomcat: Apache Tomcat Severity,\nepss: Exploit Prediction Scoring System,\nssvc: Stakeholder-Specific Vulnerability Categorization ",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.CharField(help_text="Example: 9.0, Important, High", max_length=50),
                ),
                (
                    "scoring_elements",
                    models.CharField(
                        help_text="Supporting scoring elements used to compute the score values. For example a CVSS vector string as used to compute a CVSS score.",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC Date of publication of the vulnerability severity",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["url", "scoring_system", "value"],
            },
        ),
        migrations.CreateModel(
            name="AdvisoryWeakness",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cwe_id", models.IntegerField(help_text="CWE id")),
            ],
        ),
        migrations.CreateModel(
            name="AdvisoryV2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "advisory_id",
                    models.CharField(
                        help_text="An advisory is a unique vulnerability identifier in some database, such as CVE-2020-2233",
                        max_length=50,
                    ),
                ),
                (
                    "unique_content_id",
                    models.CharField(
                        help_text="A 64 character unique identifier for the content of the advisory since we use sha256 as hex",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "affected_packages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of serializable AffectedPackage objects",
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True, help_text="UTC Date of publication of the advisory", null=True
                    ),
                ),
                (
                    "date_collected",
                    models.DateTimeField(help_text="UTC Date on which the advisory was collected"),
                ),
                (
                    "date_imported",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC Date on which the advisory was imported",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Fully qualified name of the importer prefixed with themodule name importing the advisory. Eg:vulnerabilities.pipeline.nginx_importer.NginxImporterPipeline",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(help_text="Link to the advisory on the upstream website")),
                (
                    "aliases",
                    models.ManyToManyField(
                        help_text="A list of serializable Alias objects",
                        related_name="advisories",
                        to="vulnerabilities.advisoryalias",
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        help_text="A list of serializable Reference objects",
                        related_name="advisories",
                        to="vulnerabilities.advisoryreference",
                    ),
                ),
                (
                    "severities",
                    models.ManyToManyField(
                        help_text="A list of vulnerability severities associated with this advisory.",
                        related_name="advisories",
                        to="vulnerabilities.advisoryseverity",
                    ),
                ),
                (
                    "weaknesses",
                    models.ManyToManyField(
                        help_text="A list of software weaknesses associated with this advisory.",
                        related_name="advisories",
                        to="vulnerabilities.advisoryweakness",
                    ),
                ),
            ],
            options={
                "ordering": ["date_published", "unique_content_id"],
            },
        ),
    ]
