# Generated by Django 4.2.20 on 2025-06-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_pipelineschedule_pipelinerun"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryToDo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "related_advisories_id",
                    models.CharField(
                        help_text="SHA1 digest of the unique_content_id field of the applicable advisories.",
                        max_length=40,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("MISSING_AFFECTED_PACKAGE", "Advisory is missing affected package"),
                            ("MISSING_FIXED_BY_PACKAGE", "Advisory is missing fixed-by package"),
                            (
                                "MISSING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisory is missing both affected and fixed-by packages",
                            ),
                            ("MISSING_SUMMARY", "Advisory is missing summary"),
                            (
                                "CONFLICTING_FIXED_BY_PACKAGES",
                                "Advisories have conflicting fixed-by packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_PACKAGES",
                                "Advisories have conflicting affected packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisories have conflicting affected and fixed-by packages",
                            ),
                            (
                                "CONFLICTING_SEVERITY_SCORES",
                                "Advisories have conflicting severity scores",
                            ),
                        ],
                        db_index=True,
                        help_text="Select the issue that needs to be addressed from the available options.",
                        max_length=50,
                    ),
                ),
                (
                    "issue_detail",
                    models.TextField(blank=True, help_text="Additional details about the issue."),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this TODO was created.",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, help_text="This TODO is resolved or not."
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp indicating when this TODO was resolved.",
                        null=True,
                    ),
                ),
                (
                    "resolution_detail",
                    models.TextField(
                        blank=True, help_text="Additional detail on how this TODO was resolved."
                    ),
                ),
                (
                    "advisories",
                    models.ManyToManyField(
                        help_text="Advisory/ies where this TODO is applicable.",
                        related_name="advisory_todos",
                        to="vulnerabilities.advisory",
                    ),
                ),
            ],
            options={
                "unique_together": {("related_advisories_id", "issue_type")},
            },
        ),
    ]
