# Generated by Django 4.2.20 on 2025-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_advisoryalias_advisoryreference_advisoryseverity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageV2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="A short code to identify the type of this package. For example: gem for a Rubygem, docker for a container, pypi for a Python Wheel or Egg, maven for a Maven Jar, deb for a Debian package, etc.",
                        max_length=16,
                    ),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True,
                        help_text="Package name prefix, such as Maven groupid, Docker image owner, GitHub user or organization, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Name of the package.", max_length=100),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Version of the package.", max_length=100
                    ),
                ),
                (
                    "qualifiers",
                    models.CharField(
                        blank=True,
                        help_text="Extra qualifying data for a package such as the name of an OS, architecture, distro, etc.",
                        max_length=1024,
                    ),
                ),
                (
                    "subpath",
                    models.CharField(
                        blank=True,
                        help_text="Extra subpath within a package, relative to the package root.",
                        max_length=200,
                    ),
                ),
                (
                    "package_url",
                    models.CharField(
                        db_index=True,
                        help_text="The Package URL for this package.",
                        max_length=1000,
                    ),
                ),
                (
                    "plain_package_url",
                    models.CharField(
                        db_index=True,
                        help_text="The Package URL for this package without qualifiers and subpath.",
                        max_length=1000,
                    ),
                ),
                (
                    "is_ghost",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if the package does not exist in the upstream package manager or its repository.",
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Risk score between 0.00 and 10.00, where higher values indicate greater vulnerability risk for the package.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "version_rank",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Rank of the version to support ordering by version. Rank zero means the rank has not been defined yet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="advisoryv2",
            name="affected_packages",
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="affecting_packages",
            field=models.ManyToManyField(
                help_text="A list of packages that are affected by this advisory.",
                related_name="fixing_advisories",
                to="vulnerabilities.packagev2",
            ),
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="fixed_by_packages",
            field=models.ManyToManyField(
                help_text="A list of packages that are reported by this advisory.",
                related_name="affected_by_advisories",
                to="vulnerabilities.packagev2",
            ),
        ),
    ]
