# Generated by Django 4.2.22 on 2025-06-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_pipelineschedule_pipelinerun"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiuser",
            options={
                "permissions": [
                    ("throttle_unrestricted", "Exempt from API throttling limits"),
                    ("throttle_18000_hour", "Can make 18000 API requests per hour"),
                    ("throttle_14400_hour", "Can make 14400 API requests per hour"),
                ]
            },
        ),
    ]
