# Generated by Django 4.2.20 on 2025-05-21 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_pipelineschedule_pipelinerun"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineschedule",
            name="execution_timeout",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Number hours before pipeline execution is forcefully terminated.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Pipeline timeout must be at least 1 hour."
                    ),
                    django.core.validators.MaxValueValidator(
                        72, message="Pipeline timeout must be at most 72 hours."
                    ),
                ],
            ),
        ),
    ]
