# Generated by Django 4.2.20 on 2025-05-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_advisoryalias_advisoryreference_advisoryseverity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryv2",
            name="datasource_ID",
            field=models.CharField(
                help_text="Fully qualified name of the importer prefixed with themodule name importing the advisory. Eg:nginx_importer_v2",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="fixed_by_packages",
            field=models.ManyToManyField(
                help_text="A list of packages that are reported by this advisory.",
                related_name="fixing_advisories",
                to="vulnerabilities.packagev2",
            ),
        ),
        migrations.CreateModel(
            name="AdvisoryExploit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        blank=True,
                        help_text="The date the vulnerability was added to an exploit catalog.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the vulnerability in an exploit catalog, often a refinement of the original CVE description",
                        null=True,
                    ),
                ),
                (
                    "required_action",
                    models.TextField(
                        blank=True,
                        help_text="The required action to address the vulnerability, typically to apply vendor updates or apply vendor mitigations or to discontinue use.",
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the required action is due, which applies to all USA federal civilian executive branch (FCEB) agencies, but all organizations are strongly encouraged to execute the required action",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes and resources about the vulnerability, often a URL to vendor instructions.",
                        null=True,
                    ),
                ),
                (
                    "known_ransomware_campaign_use",
                    models.BooleanField(
                        default=False,
                        help_text="Known' if this vulnerability is known to have been leveraged as part of a ransomware campaign; \n        or 'Unknown' if there is no confirmation that the vulnerability has been utilized for ransomware.",
                    ),
                ),
                (
                    "source_date_published",
                    models.DateField(
                        blank=True,
                        help_text="The date that the exploit was published or disclosed.",
                        null=True,
                    ),
                ),
                (
                    "exploit_type",
                    models.TextField(
                        blank=True,
                        help_text="The type of the exploit as provided by the original upstream data source.",
                        null=True,
                    ),
                ),
                (
                    "platform",
                    models.TextField(
                        blank=True,
                        help_text="The platform associated with the exploit as provided by the original upstream data source.",
                        null=True,
                    ),
                ),
                (
                    "source_date_updated",
                    models.DateField(
                        blank=True,
                        help_text="The date the exploit was updated in the original upstream data source.",
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.TextField(
                        blank=True,
                        help_text="The source of the exploit information, such as CISA KEV, exploitdb, metaspoit, or others.",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to the exploit as provided in the original upstream data source.",
                        null=True,
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exploits",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
