# Generated by Django 4.2.20 on 2025-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0092_advisoryalias_advisoryreference_advisoryseverity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryreference",
            name="reference_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="An optional reference ID, such as DSA-4465-1 when available",
                max_length=500,
            ),
        ),
    ]
