# Generated by Django 4.2.20 on 2025-05-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0093_pipelineschedule_execution_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineschedule",
            name="live_logging",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When enabled logs will be streamed live during pipeline execution. For legacy importers and improvers, logs are always made available only after execution completes.",
            ),
        ),
    ]
