# Generated by Django 4.2.22 on 2025-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0094_advisoryalias_advisoryreference_advisoryseverity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiuser",
            options={
                "permissions": [
                    (
                        "throttle_3_unrestricted",
                        "Can make unlimited API requests without any throttling limits",
                    ),
                    (
                        "throttle_2_high",
                        "Can make high number of API requests with minimal throttling",
                    ),
                    (
                        "throttle_1_medium",
                        "Can make medium number of API requests with standard throttling",
                    ),
                    (
                        "throttle_0_low",
                        "Can make low number of API requests with strict throttling",
                    ),
                ]
            },
        ),
    ]
