# Generated by Django 4.2.22 on 2025-07-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0096_alter_pipelineschedule_run_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryv2",
            name="advisory_id",
            field=models.CharField(
                help_text="An advisory is a unique vulnerability identifier in some database, such as PYSEC-2020-2233",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="datasource_id",
            field=models.CharField(
                help_text="Unique ID for the datasource used for this advisory .e.g.: nginx_importer_v2",
                max_length=200,
            ),
        ),
    ]
