# Generated by Django 4.2.22 on 2025-07-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0097_alter_advisoryv2_advisory_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisory",
            options={
                "ordering": ["date_published", "unique_content_id"],
                "verbose_name_plural": "Advisories",
            },
        ),
        migrations.AlterModelOptions(
            name="advisoryalias",
            options={"ordering": ["alias"], "verbose_name_plural": "Advisory aliases"},
        ),
        migrations.AlterModelOptions(
            name="advisoryseverity",
            options={
                "ordering": ["url", "scoring_system", "value"],
                "verbose_name_plural": "Advisory severities",
            },
        ),
        migrations.AlterModelOptions(
            name="advisoryweakness",
            options={"verbose_name_plural": "Advisory weaknesses"},
        ),
        migrations.AlterModelOptions(
            name="alias",
            options={"ordering": ["alias"], "verbose_name_plural": "Aliases"},
        ),
        migrations.AlterModelOptions(
            name="vulnerabilityseverity",
            options={
                "ordering": ["url", "scoring_system", "value"],
                "verbose_name_plural": "Vulnerability severities",
            },
        ),
        migrations.AlterModelOptions(
            name="weakness",
            options={"verbose_name_plural": "Weaknesses"},
        ),
    ]
