# Generated by Django 4.2.22 on 2025-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0098_alter_advisory_options_alter_advisoryalias_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="original_advisory_text",
            field=models.TextField(
                blank=True,
                help_text="Raw advisory data as collected from the upstream datasource.",
                null=True,
            ),
        ),
    ]
