# Generated by Django 4.2.22 on 2025-07-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0099_advisoryv2_original_advisory_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisoryv2",
            name="affecting_packages",
        ),
        migrations.RemoveField(
            model_name="advisoryv2",
            name="fixed_by_packages",
        ),
        migrations.CreateModel(
            name="ImpactedPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_purl",
                    models.CharField(
                        blank=True,
                        help_text="Version less PURL related to impacted range.",
                        max_length=500,
                    ),
                ),
                (
                    "affecting_vers",
                    models.CharField(
                        blank=True,
                        help_text="VersionRange expression for package vulnerable to this impact.",
                        max_length=500,
                    ),
                ),
                (
                    "fixed_vers",
                    models.CharField(
                        blank=True,
                        help_text="VersionRange expression for packages fixing the vulnerable package in this impact.",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp indicating when this impact was added.",
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacted_packages",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
                (
                    "affecting_packages",
                    models.ManyToManyField(
                        help_text="Packages vulnerable to this impact.",
                        related_name="affected_in_impacts",
                        to="vulnerabilities.packagev2",
                    ),
                ),
                (
                    "fixed_by_packages",
                    models.ManyToManyField(
                        help_text="Packages vulnerable to this impact.",
                        related_name="fixed_in_impacts",
                        to="vulnerabilities.packagev2",
                    ),
                ),
            ],
        ),
    ]
