# Generated by Django 4.2.22 on 2025-08-25 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0101_advisorytodov2_todorelatedadvisoryv2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivePipelineRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_date", models.DateTimeField(blank=True, editable=False, null=True)),
                ("status", models.CharField(default="queued", max_length=20)),
                ("purl", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="pipelinerun",
            name="live_pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipelineruns",
                to="vulnerabilities.livepipelinerun",
            ),
        ),
    ]
