# Generated by Django 4.2.22 on 2025-09-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0101_advisorytodov2_todorelatedadvisoryv2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactedpackage",
            name="affecting_vers",
            field=models.TextField(
                blank=True,
                help_text="VersionRange expression for package vulnerable to this impact.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="impactedpackage",
            name="base_purl",
            field=models.CharField(
                help_text="Version less PURL related to impacted range.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="impactedpackage",
            name="fixed_vers",
            field=models.TextField(
                blank=True,
                help_text="VersionRange expression for packages fixing the vulnerable package in this impact.",
                null=True,
            ),
        ),
    ]
