# Generated by Django 4.2.22 on 2025-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0102_alter_impactedpackage_affecting_vers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeCommit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="Unique commit identifier (e.g., SHA).", max_length=64
                    ),
                ),
                (
                    "vcs_url",
                    models.URLField(
                        help_text="URL of the repository containing the commit.", max_length=1024
                    ),
                ),
                (
                    "commit_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Rank of the commit to support ordering by commit. Rank zero means the rank has not been defined yet",
                    ),
                ),
                (
                    "commit_author",
                    models.CharField(
                        blank=True, help_text="Author of the commit.", max_length=100, null=True
                    ),
                ),
                (
                    "commit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp indicating when this commit was created.",
                        null=True,
                    ),
                ),
                (
                    "commit_message",
                    models.TextField(
                        blank=True, help_text="Commit message or description.", null=True
                    ),
                ),
            ],
            options={
                "unique_together": {("commit_hash", "vcs_url")},
            },
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="affecting_commits",
            field=models.ManyToManyField(
                help_text="Commits introducing this impact.",
                related_name="affecting_commits_in_impacts",
                to="vulnerabilities.codecommit",
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="fixed_by_commits",
            field=models.ManyToManyField(
                help_text="Commits fixing this impact.",
                related_name="fixing_commits_in_impacts",
                to="vulnerabilities.codecommit",
            ),
        ),
    ]
