# Generated by Django 4.2.25 on 2025-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0103_codecommit_impactedpackage_affecting_commits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSVC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "vector",
                    models.CharField(
                        help_text="The vector string representing the SSVC.", max_length=255
                    ),
                ),
                (
                    "options",
                    models.JSONField(help_text="A JSON object containing the SSVC options."),
                ),
                (
                    "decision",
                    models.CharField(help_text="The decision string for the SSVC.", max_length=255),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        help_text="The advisory associated with this SSVC.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssvc_entries",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
            options={
                "unique_together": {("vector", "advisory", "decision")},
            },
        ),
    ]
