# Generated by Django 4.2.25 on 2025-12-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0103_codecommit_impactedpackage_affecting_commits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryPOC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField()),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pocs",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
