# Generated by Django 4.2.25 on 2025-12-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0103_codecommit_impactedpackage_affecting_commits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryDetectionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_text",
                    models.TextField(
                        help_text="Full text of the detection rule, script, or signature."
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yara", "YARA"),
                            ("sigma", "Sigma Detection Rule"),
                            ("clamav", "ClamAV Signature"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL or reference to the source of the rule (vendor feed, GitHub repo, etc.).",
                        null=True,
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_rules",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
