# Generated by Django 4.2.25 on 2025-12-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0103_codecommit_impactedpackage_affecting_commits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("yara", "Yara"),
                            ("yara-x", "Yara-X"),
                            ("sigma", "Sigma"),
                            ("clamav", "ClamAV"),
                            ("suricata", "Suricata"),
                        ],
                        help_text="The type of the detection rule content (e.g., YARA, Sigma).",
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL to the original source or reference for this rule.",
                        max_length=1024,
                    ),
                ),
                (
                    "rule_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional structured data such as tags, or author information.",
                        null=True,
                    ),
                ),
                (
                    "rule_text",
                    models.TextField(help_text="The content of the detection signature."),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detection_rules",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
