# Generated by Django 4.2.25 on 2025-12-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0103_codecommit_impactedpackage_affecting_commits_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageCommitPatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="The commit hash of the patch in the VCS.", max_length=128
                    ),
                ),
                (
                    "vcs_url",
                    models.URLField(
                        help_text="The Version Control System URL (e.g., git repo URL).",
                        max_length=1024,
                    ),
                ),
                ("patch_text", models.TextField(blank=True, null=True)),
                ("patch_checksum", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "unique_together": {("commit_hash", "vcs_url")},
            },
        ),
        migrations.CreateModel(
            name="Patch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "patch_url",
                    models.URLField(
                        blank=True, help_text="URL to the patch file or diff.", null=True
                    ),
                ),
                (
                    "patch_text",
                    models.TextField(
                        blank=True,
                        help_text="The actual text content of the code patch/diff.",
                        null=True,
                    ),
                ),
                (
                    "patch_checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA512 checksum of the patch content.",
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("patch_checksum", "patch_url")},
            },
        ),
        migrations.RemoveField(
            model_name="impactedpackage",
            name="affecting_commits",
        ),
        migrations.RemoveField(
            model_name="impactedpackage",
            name="fixed_by_commits",
        ),
        migrations.DeleteModel(
            name="CodeCommit",
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="patches",
            field=models.ManyToManyField(
                help_text="A list of patches associated with this advisory.",
                related_name="advisories",
                to="vulnerabilities.patch",
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="fixed_by_package_commit_patches",
            field=models.ManyToManyField(
                help_text="PackageCommitPatches that fix this impact.",
                related_name="fixed_in_impacts",
                to="vulnerabilities.packagecommitpatch",
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="introduced_by_package_commit_patches",
            field=models.ManyToManyField(
                help_text="PackageCommitPatches that introduce this impact.",
                related_name="introduced_in_impacts",
                to="vulnerabilities.packagecommitpatch",
            ),
        ),
    ]
