# Generated by Django 4.2.25 on 2025-12-01 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0104_advisorydetectionrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorydetectionrule",
            name="advisory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_rules",
                to="vulnerabilities.advisoryv2",
            ),
        ),
    ]
