# Generated by Django 4.2.25 on 2025-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0104_ssvc"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageCommitPatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "commit_hash",
                    models.CharField(
                        help_text="The commit hash of the patch in the VCS.", max_length=128
                    ),
                ),
                (
                    "vcs_url",
                    models.URLField(
                        help_text="The Version Control System URL (e.g., git repo URL).",
                        max_length=1024,
                    ),
                ),
                ("patch_text", models.TextField(blank=True, null=True)),
                ("patch_checksum", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "patch_url",
                    models.URLField(
                        blank=True, help_text="URL to the patch file or diff.", null=True
                    ),
                ),
                (
                    "patch_text",
                    models.TextField(
                        blank=True,
                        help_text="The actual text content of the code patch/diff.",
                        null=True,
                    ),
                ),
                (
                    "patch_checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA512 checksum of the patch content.",
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="impactedpackage",
            name="affecting_commits",
        ),
        migrations.RemoveField(
            model_name="impactedpackage",
            name="fixed_by_commits",
        ),
        migrations.AlterField(
            model_name="advisoryreference",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("advisory", "Advisory"),
                    ("exploit", "Exploit"),
                    ("commit", "Commit"),
                    ("mailing_list", "Mailing List"),
                    ("bug", "Bug"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="CodeCommit",
        ),
        migrations.AddConstraint(
            model_name="patch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("patch_url__isnull", False), models.Q(("patch_url", ""), _negated=True)
                    ),
                    models.Q(
                        ("patch_text__isnull", False), models.Q(("patch_text", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="patch_url_or_patch_text",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patch",
            unique_together={("patch_checksum", "patch_url")},
        ),
        migrations.AlterUniqueTogether(
            name="packagecommitpatch",
            unique_together={("commit_hash", "vcs_url")},
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="patches",
            field=models.ManyToManyField(
                help_text="A list of patches associated with this advisory.",
                related_name="advisories",
                to="vulnerabilities.patch",
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="fixed_by_package_commit_patches",
            field=models.ManyToManyField(
                help_text="PackageCommitPatches that fix this impact.",
                related_name="fixed_in_impacts",
                to="vulnerabilities.packagecommitpatch",
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="introduced_by_package_commit_patches",
            field=models.ManyToManyField(
                help_text="PackageCommitPatches that introduce this impact.",
                related_name="introduced_in_impacts",
                to="vulnerabilities.packagecommitpatch",
            ),
        ),
    ]
