# Generated by Django 4.2.25 on 2025-12-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0105_packagecommitpatch_patch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryseverity",
            name="scoring_elements",
            field=models.CharField(
                help_text="Supporting scoring elements used to compute the score values. For example a CVSS vector string as used to compute a CVSS score.",
                max_length=200,
                null=True,
            ),
        ),
    ]
