# Generated by Django 4.2.25 on 2025-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0105_packagecommitpatch_patch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryreference",
            name="url",
            field=models.URLField(help_text="URL to the vulnerability reference", max_length=1024),
        ),
        migrations.AlterField(
            model_name="advisoryseverity",
            name="value",
            field=models.CharField(
                help_text="Example: 9.0, Important, High", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="advisoryweakness",
            name="cwe_id",
            field=models.IntegerField(help_text="CWE id", unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="advisoryreference",
            unique_together={("url", "reference_type")},
        ),
        migrations.AlterUniqueTogether(
            name="advisoryseverity",
            unique_together={
                ("url", "scoring_system", "value", "scoring_elements", "published_at")
            },
        ),
        migrations.AddConstraint(
            model_name="advisoryseverity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("value__isnull", False), models.Q(("value", ""), _negated=True)),
                    models.Q(
                        ("scoring_elements__isnull", False),
                        models.Q(("scoring_elements", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="scoring_elements_or_value_must_be_set",
            ),
        ),
    ]
