# Generated by Django 4.2.25 on 2025-12-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0106_alter_advisoryreference_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisoryv2",
            name="date_imported",
        ),
    ]
