# Generated by Django 4.2.25 on 2025-12-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0107_remove_advisoryv2_date_imported"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="advisoryv2",
            index=models.Index(
                fields=["avid", "-date_collected", "-id"], name="advisory_latest_by_avid_idx"
            ),
        ),
    ]
