# Generated by Django 4.2.25 on 2025-12-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0108_advisoryv2_advisory_latest_by_avid_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryseverity",
            name="scoring_elements",
            field=models.CharField(
                help_text="Supporting scoring elements used to compute the score values. For example a CVSS vector string as used to compute a CVSS score.",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityseverity",
            name="scoring_elements",
            field=models.CharField(
                help_text="Supporting scoring elements used to compute the score values. For example a CVSS vector string as used to compute a CVSS score.",
                max_length=250,
                null=True,
            ),
        ),
    ]
