# Generated by Django 4.2.22 on 2026-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0109_alter_advisoryseverity_scoring_elements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelineschedule",
            name="is_run_once",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When set to True, this Pipeline will run only once.",
            ),
        ),
    ]
