# Generated by Django 4.2.25 on 2026-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0111_alter_advisoryseverity_scoring_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisoryseverity",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("cvssv2", "CVSSv2 Base Score"),
                    ("cvssv3", "CVSSv3 Base Score"),
                    ("cvssv3.1", "CVSSv3.1 Base Score"),
                    ("cvssv4", "CVSSv4 Base Score"),
                    ("rhbs", "RedHat Bugzilla severity"),
                    ("rhas", "RedHat Aggregate severity"),
                    ("archlinux", "Archlinux Vulnerability Group Severity"),
                    ("cvssv3.1_qr", "CVSSv3.1 Qualitative Severity Rating"),
                    ("generic_textual", "Generic textual severity rating"),
                    ("apache_httpd", "Apache Httpd Severity"),
                    ("apache_tomcat", "Apache Tomcat Severity"),
                    ("epss", "Exploit Prediction Scoring System"),
                    ("ssvc", "Stakeholder-Specific Vulnerability Categorization"),
                    ("openssl", "OpenSSL Severity"),
                    ("ubuntu", "Ubuntu priority"),
                ],
                help_text="Identifier for the scoring system used. Available choices are: cvssv2: CVSSv2 Base Score,\ncvssv3: CVSSv3 Base Score,\ncvssv3.1: CVSSv3.1 Base Score,\ncvssv4: CVSSv4 Base Score,\nrhbs: RedHat Bugzilla severity,\nrhas: RedHat Aggregate severity,\narchlinux: Archlinux Vulnerability Group Severity,\ncvssv3.1_qr: CVSSv3.1 Qualitative Severity Rating,\ngeneric_textual: Generic textual severity rating,\napache_httpd: Apache Httpd Severity,\napache_tomcat: Apache Tomcat Severity,\nepss: Exploit Prediction Scoring System,\nssvc: Stakeholder-Specific Vulnerability Categorization,\nopenssl: OpenSSL Severity,\nubuntu: Ubuntu priority ",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityseverity",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("cvssv2", "CVSSv2 Base Score"),
                    ("cvssv3", "CVSSv3 Base Score"),
                    ("cvssv3.1", "CVSSv3.1 Base Score"),
                    ("cvssv4", "CVSSv4 Base Score"),
                    ("rhbs", "RedHat Bugzilla severity"),
                    ("rhas", "RedHat Aggregate severity"),
                    ("archlinux", "Archlinux Vulnerability Group Severity"),
                    ("cvssv3.1_qr", "CVSSv3.1 Qualitative Severity Rating"),
                    ("generic_textual", "Generic textual severity rating"),
                    ("apache_httpd", "Apache Httpd Severity"),
                    ("apache_tomcat", "Apache Tomcat Severity"),
                    ("epss", "Exploit Prediction Scoring System"),
                    ("ssvc", "Stakeholder-Specific Vulnerability Categorization"),
                    ("openssl", "OpenSSL Severity"),
                    ("ubuntu", "Ubuntu priority"),
                ],
                help_text="Identifier for the scoring system used. Available choices are: cvssv2: CVSSv2 Base Score,\ncvssv3: CVSSv3 Base Score,\ncvssv3.1: CVSSv3.1 Base Score,\ncvssv4: CVSSv4 Base Score,\nrhbs: RedHat Bugzilla severity,\nrhas: RedHat Aggregate severity,\narchlinux: Archlinux Vulnerability Group Severity,\ncvssv3.1_qr: CVSSv3.1 Qualitative Severity Rating,\ngeneric_textual: Generic textual severity rating,\napache_httpd: Apache Httpd Severity,\napache_tomcat: Apache Tomcat Severity,\nepss: Exploit Prediction Scoring System,\nssvc: Stakeholder-Specific Vulnerability Categorization,\nopenssl: OpenSSL Severity,\nubuntu: Ubuntu priority ",
                max_length=50,
            ),
        ),
    ]
