# Generated by Django 5.2.11 on 2026-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0112_alter_advisoryseverity_scoring_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryseverity',
            name='scoring_elements_data',
            field=models.JSONField(blank=True, default=dict, help_text='Serialized scoring elements data.'),
        ),
        migrations.AddField(
            model_name='vulnerabilityseverity',
            name='scoring_elements_data',
            field=models.JSONField(blank=True, default=dict, help_text='Serialized scoring elements data.'),
        ),
    ]
