# Generated by Django 4.2.25 on 2026-02-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0112_alter_advisoryseverity_scoring_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="precedence",
            field=models.IntegerField(
                blank=True,
                help_text="Precedence indicates the priority of advisory from different datasources. It is determined based on the reliability of the datasource and how close it is to the source.",
                null=True,
            ),
        ),
    ]
