# Generated by Django 5.2.11 on 2026-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0113_advisoryv2_precedence"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="related_advisory_severities",
            field=models.ManyToManyField(
                help_text="Related advisories that are used to calculate the severity of this advisory.",
                related_name="related_to_advisory_severities",
                to="vulnerabilities.advisoryv2",
            ),
        ),
    ]
