# Generated by Django 5.2.11 on 2026-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0115_impactedpackageaffecting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="advisory_content_hash",
            field=models.CharField(
                blank=True,
                help_text="A unique hash computed from the content of the advisory used to identify advisories with the same content.",
                max_length=64,
                null=True,
            ),
        ),
    ]
