# Generated by Django 5.2.11 on 2026-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0116_detectionrule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectionrule",
            name="advisory",
        ),
        migrations.AddField(
            model_name="detectionrule",
            name="related_advisories",
            field=models.ManyToManyField(
                help_text="Advisories associated with this DetectionRule.",
                related_name="detection_rules",
                to="vulnerabilities.advisoryv2",
            ),
        ),
    ]
