# Generated by Django 5.2.11 on 2026-03-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0116_advisoryv2_advisory_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="risk_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Risk expressed as a number ranging from 0 to 10. Risk is calculated from weighted severity and exploitability values. It is the maximum value of (the weighted severity multiplied by its exploitability) or 10. Risk = min(weighted severity * exploitability, 10)",
                max_digits=3,
                null=True,
            ),
        ),
    ]
