# Generated by Django 5.2.11 on 2026-03-25 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0117_advisoryv2_risk_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorySet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("affecting", "Affecting"), ("fixing", "Fixing")], max_length=20
                    ),
                ),
                ("identifiers", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vulnerabilities.packagev2"
                    ),
                ),
                (
                    "primary_advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="vulnerabilities.advisoryv2"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvisorySetMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vulnerabilities.advisoryv2"
                    ),
                ),
                (
                    "advisory_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="vulnerabilities.advisoryset",
                    ),
                ),
            ],
        ),
    ]
