# Generated by Django 5.2.11 on 2026-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0118_advisoryset_advisorysetmember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisoryset",
            name="identifiers",
        ),
        migrations.RemoveField(
            model_name="advisoryv2",
            name="advisory_content_hash",
        ),
        migrations.AddField(
            model_name="advisoryset",
            name="aliases",
            field=models.ManyToManyField(
                help_text="A list of serializable Alias objects",
                related_name="advisory_sets",
                to="vulnerabilities.advisoryalias",
            ),
        ),
    ]
