# Generated by Django 5.2.11 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0119_remove_advisoryset_identifiers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryreference",
            name="archive_url",
            field=models.URLField(
                help_text="URL to the backup vulnerability reference", max_length=1024, null=True
            ),
        ),
    ]
