# Generated by Django 5.2.11 on 2026-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0119_remove_advisoryset_identifiers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactedpackage",
            name="last_range_unfurl_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the last vers range unfurl.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="impactedpackage",
            name="last_successful_range_unfurl_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the last successful vers range unfurl.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pipelineschedule",
            name="run_priority",
            field=models.IntegerField(
                choices=[(1, "high"), (2, "default")],
                default=2,
                help_text="Select the pipeline execution priority",
            ),
        ),
    ]
