# Generated by Django 5.2.11 on 2026-04-13 19:05

from django.db import migrations
from django.db import models
from django.db.models import F


class Migration(migrations.Migration):
    def add_is_latest_on_existing_advisory(apps, schema_editor):
        Advisory = apps.get_model("vulnerabilities", "AdvisoryV2")

        print(f"\nUpdating is_latest on existing V2 Advisory.")
        latest_qs = Advisory.objects.order_by(
            "avid",
            F("date_collected").desc(nulls_last=True),
            "-id",
        ).distinct("avid")

        Advisory.objects.filter(id__in=latest_qs.values("id")).update(is_latest=True)

    dependencies = [
        ("vulnerabilities", "0120_impactedpackage_last_range_unfurl_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="is_latest",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this is the latest version of the advisory identified by its AVID.",
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="advisory_id",
            field=models.CharField(
                db_index=True,
                help_text="An advisory is a unique vulnerability identifier in some database, such as PYSEC-2020-2233",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="datasource_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique ID for the datasource used for this advisory .e.g.: nginx_importer_v2",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="advisoryv2",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest", True)),
                fields=("avid",),
                name="unique_latest_per_avid",
            ),
        ),
        migrations.RunPython(
            code=add_is_latest_on_existing_advisory,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
