# Generated by Django 5.2.11 on 2026-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0120_impactedpackage_last_range_unfurl_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactedpackage",
            name="last_successful_range_unfurl_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Timestamp of the last successful vers range unfurl.",
                null=True,
            ),
        ),
    ]
