# Generated by Django 5.2.11 on 2026-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0122_auto_20260415_1155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagev2",
            options={
                "ordering": [
                    "type",
                    "namespace",
                    "name",
                    "version_rank",
                    "version",
                    "qualifiers",
                    "subpath",
                ]
            },
        ),
        migrations.AlterField(
            model_name="packagev2",
            name="package_url",
            field=models.CharField(
                db_index=True,
                help_text="The Package URL for this package.",
                max_length=1000,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packagev2",
            unique_together={("type", "namespace", "name", "version", "qualifiers", "subpath")},
        ),
        migrations.AddIndex(
            model_name="packagev2",
            index=models.Index(
                fields=["type", "namespace", "name"], name="vulnerabili_type_ca0efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagev2",
            index=models.Index(
                fields=["type", "namespace", "name", "qualifiers", "subpath"],
                name="vulnerabili_type_c98c98_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packagev2",
            index=models.Index(
                fields=["type", "namespace", "name", "version"], name="vulnerabili_type_1af1cc_idx"
            ),
        ),
    ]
