# Generated by Django 5.2.11 on 2026-04-27 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0123_alter_packagev2_options_alter_packagev2_package_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdvisoryToDoV2",
        ),
        migrations.DeleteModel(
            name="ToDoRelatedAdvisoryV2",
        ),
        migrations.CreateModel(
            name="AdvisoryToDoV2",
            fields=[
                (
                    "todo_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "related_advisories_id",
                    models.CharField(
                        help_text="SHA1 digest of the unique_content_id field of the applicable advisories.",
                        max_length=40,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        db_index=True,
                        help_text="Alias associated with TODO advisories",
                        max_length=50,
                    ),
                ),
                (
                    "advisories_count",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="Number of advisory associated with this TODO.",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("MISSING_AFFECTED_PACKAGE", "Advisory is missing affected package"),
                            ("MISSING_FIXED_BY_PACKAGE", "Advisory is missing fixed-by package"),
                            (
                                "MISSING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisory is missing both affected and fixed-by packages",
                            ),
                            ("MISSING_SUMMARY", "Advisory is missing summary"),
                            (
                                "CONFLICTING_FIXED_BY_PACKAGES",
                                "Advisories have conflicting fixed-by packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_PACKAGES",
                                "Advisories have conflicting affected packages",
                            ),
                            (
                                "CONFLICTING_AFFECTED_AND_FIXED_BY_PACKAGES",
                                "Advisories have conflicting affected and fixed-by packages",
                            ),
                            (
                                "CONFLICTING_SEVERITY_SCORES",
                                "Advisories have conflicting severity scores",
                            ),
                        ],
                        db_index=True,
                        help_text="Select the issue that needs to be addressed from the available options.",
                        max_length=50,
                    ),
                ),
                (
                    "issue_detail",
                    models.TextField(blank=True, help_text="Additional details about the issue."),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this TODO was created.",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True, default=False, help_text="This TODO is resolved or not."
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp indicating when this TODO was resolved.",
                        null=True,
                    ),
                ),
                (
                    "resolution_detail",
                    models.TextField(
                        blank=True, help_text="Additional detail on how this TODO was resolved."
                    ),
                ),
                (
                    "oldest_advisory_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp indicating when the oldest advisory was published, used for triaging TODOs.",
                        null=True,
                    ),
                ),
                (
                    "is_todo_stale",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="TODOs are marked stale if associate advisory is no longer the latest version of the advisory.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToDoRelatedAdvisoryV2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vulnerabilities.advisoryv2"
                    ),
                ),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vulnerabilities.advisorytodov2",
                    ),
                ),
            ],
            options={
                "unique_together": {("todo", "advisory")},
            },
        ),
        migrations.AddField(
            model_name="advisorytodov2",
            name="advisories",
            field=models.ManyToManyField(
                help_text="Advisory/ies where this TODO is applicable.",
                related_name="advisory_todos",
                through="vulnerabilities.ToDoRelatedAdvisoryV2",
                to="vulnerabilities.advisoryv2",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="advisorytodov2",
            unique_together={("related_advisories_id", "issue_type")},
        ),
    ]
