# Generated by Django 5.2.11 on 2026-05-01 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0124_advisoryv2_remove_malformed_aliases_and_dvisory_id"),
    ]

    def clean_empty_vers_range(apps, _):
        ImpactedPackage = apps.get_model("vulnerabilities", "ImpactedPackage")

        ImpactedPackage.objects.filter(affecting_vers__regex=r"vers:[^/]+/$").update(
            affecting_vers=None
        )
        ImpactedPackage.objects.filter(fixed_vers__regex=r"vers:[^/]+/$").update(fixed_vers=None)

        ImpactedPackage.objects.filter(
            affecting_vers__isnull=True,
            fixed_vers__isnull=True,
            introduced_by_package_commit_patches__isnull=True,
            fixed_by_package_commit_patches__isnull=True,
        ).distinct().delete()

    operations = [
        migrations.RunPython(clean_empty_vers_range, reverse_code=migrations.RunPython.noop),
    ]
