# Generated by Django 5.2.11 on 2026-05-04 09:51

from django.db import migrations
from django.db.models import F
from django.db.models import Q
from django.db.models import Value
from django.db.models.functions import Replace


class Migration(migrations.Migration):

    def update_alpine_scheme_to_apk(apps, schema_editor):
        ImpactedPackage = apps.get_model("vulnerabilities", "ImpactedPackage")

        ImpactedPackage.objects.filter(
            Q(affecting_vers__startswith="vers:alpine/") | Q(fixed_vers__startswith="vers:alpine/")
        ).update(
            affecting_vers=Replace(F("affecting_vers"), Value("vers:alpine/"), Value("vers:apk/")),
            fixed_vers=Replace(F("fixed_vers"), Value("vers:alpine/"), Value("vers:apk/")),
        )

    def reverse_update_alpine_scheme_to_apk(apps, schema_editor):
        ImpactedPackage = apps.get_model("vulnerabilities", "ImpactedPackage")

        ImpactedPackage.objects.filter(
            Q(affecting_vers__startswith="vers:apk/") | Q(fixed_vers__startswith="vers:apk/")
        ).update(
            affecting_vers=Replace(F("affecting_vers"), Value("vers:apk/"), Value("vers:alpine/")),
            fixed_vers=Replace(F("fixed_vers"), Value("vers:apk/"), Value("vers:alpine/")),
        )

    dependencies = [
        ("vulnerabilities", "0125_clean_vers_range_without_constraints"),
    ]

    operations = [
        migrations.RunPython(
            update_alpine_scheme_to_apk,
            reverse_code=reverse_update_alpine_scheme_to_apk,
        ),
    ]
