# Generated by Django 5.2.11 on 2026-05-15 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0127_advisorytodov2_todorelatedadvisoryv2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryPOC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this POC was created.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when this POC was last updated.",
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL of the PoC, such as a repository or resource link."
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether this POC has been verified or confirmed.",
                    ),
                ),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pocs",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
