# Generated by Django 5.2.11 on 2026-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0129_advisorypoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("yara", "Yara"),
                            ("yara-x", "Yara-X"),
                            ("sigma", "Sigma"),
                            ("clamav", "ClamAV"),
                            ("suricata", "Suricata"),
                        ],
                        help_text="The type of the detection rule content (e.g., YARA, Sigma).",
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL to the original source or reference for this rule.",
                        max_length=1024,
                    ),
                ),
                (
                    "rule_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional structured data such as tags, or author information.",
                        null=True,
                    ),
                ),
                (
                    "rule_text",
                    models.TextField(help_text="The content of the detection signature."),
                ),
                (
                    "related_advisories",
                    models.ManyToManyField(
                        help_text="Advisories associated with this DetectionRule.",
                        related_name="detection_rules",
                        to="vulnerabilities.advisoryv2",
                    ),
                ),
            ],
        ),
    ]
