# Generated by Django 5.2.11 on 2026-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0129_advisorypoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="pipeline_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique ID for the pipeline used for this advisory .e.g.: nginx_importer_v2",
                max_length=200,
                null=True,
            ),
        ),
    ]
