# Generated by Django 5.2.11 on 2026-05-18 08:54

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0130_advisoryv2_pipeline_id"),
    ]

    def populate_pipeline_id(apps, schema_editor):
        Advisory = apps.get_model("vulnerabilities", "AdvisoryV2")

        Advisory.objects.update(
            pipeline_id=F("datasource_id")
        )

        assert not Advisory.objects.filter(pipeline_id="").exists(), "Some advisories have an empty pipeline_id after the update"

    operations = [
        migrations.RunPython(populate_pipeline_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="advisoryv2",
            name="pipeline_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique ID for the pipeline used for this advisory .e.g.: nginx_importer_v2",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="datasource_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique ID for the datasource used for this advisory .e.g.: nginx",
                max_length=200,
            ),
        ),
    ]
