# Generated by Django 5.2.11 on 2026-05-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0132_migrate_advisoryv2_datasource_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorytodov2",
            name="issue_detail",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional details about the issue."
            ),
        ),
    ]
