# Generated by Django 5.2.11 on 2026-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0133_alter_advisorytodov2_issue_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="_all_impacts_unfurled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Indicates whether all impacts for this advisory have been unfurled.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="_all_impacts_unfurled_successfully_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Indicates whether all impacts for this advisory have been unfurled successfully.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryset",
            name="relation_type",
            field=models.CharField(
                choices=[("affecting", "Affecting"), ("fixing", "Fixing")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="advisory_id",
            field=models.CharField(
                db_index=True,
                help_text="An advisory is a unique vulnerability identifier in some database, such as PYSEC-2020-2233",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="avid",
            field=models.CharField(
                help_text="Unique ID for the datasource used for this advisory .e.g.: pysec_importer_v2/PYSEC-2020-2233",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="datasource_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique ID for the datasource used for this advisory .e.g.: nginx",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="advisoryv2",
            name="pipeline_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique ID for the pipeline used for this advisory .e.g.: nginx_importer_v2",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="advisoryset",
            unique_together={("package", "relation_type", "primary_advisory")},
        ),
        migrations.AddIndex(
            model_name="advisoryset",
            index=models.Index(
                fields=["package", "relation_type"], name="vulnerabili_package_13a5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryv2",
            index=models.Index(
                fields=["_all_impacts_unfurled_at", "id"], name="advisory_unfurled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advisoryv2",
            index=models.Index(
                fields=["is_latest", "_all_impacts_unfurled_at"],
                name="vulnerabili_is_late_564f3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="impactedpackage",
            index=models.Index(
                fields=["advisory", "last_range_unfurl_at"], name="vulnerabili_advisor_1e3414_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impactedpackageaffecting",
            index=models.Index(
                fields=["package", "impacted_package"], name="vulnerabili_package_22fb39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impactedpackageaffecting",
            index=models.Index(
                fields=["impacted_package", "package"], name="vulnerabili_impacte_1904b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impactedpackagefixedby",
            index=models.Index(
                fields=["package", "impacted_package"], name="vulnerabili_package_f6588f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="impactedpackagefixedby",
            index=models.Index(
                fields=["impacted_package", "package"], name="vulnerabili_impacte_390971_idx"
            ),
        ),
    ]
