# Generated by Django 5.2.11 on 2026-06-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0133_alter_advisorytodov2_issue_detail"),
    ]

    def update_cvss_scoring_system(apps, schema_editor):
        AdvisorySeverity = apps.get_model("vulnerabilities", "AdvisorySeverity")

        AdvisorySeverity.objects.filter(
            scoring_system="cvssv3.1",
            scoring_elements__startswith="CVSS:3.0/",
        ).update(scoring_system="cvssv3")

    operations = [
        migrations.RunPython(
            update_cvss_scoring_system,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
