# Generated by Django 5.2.11 on 2026-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0135_advisoryexploit_record_id_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="advisorysetmember",
            constraint=models.UniqueConstraint(
                fields=("advisory_set", "advisory"), name="unique_advisory_per_set"
            ),
        ),
    ]
