# Generated by Django 5.2.11 on 2026-06-16 12:29

import django.core.validators
from django.db import migrations
from django.db import models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0136_advisorysetmember_unique_advisory_per_set"),
    ]

    def convert_hours_to_minutes(apps, schema_editor):
        PipelineSchedule = apps.get_model("vulnerabilities", "PipelineSchedule")
        PipelineSchedule.objects.update(run_interval=F("run_interval") * 60)

    def revert_convert_hours_to_minutes(apps, schema_editor):
        PipelineSchedule = apps.get_model("vulnerabilities", "PipelineSchedule")
        for schedule in PipelineSchedule.objects.all():
            schedule.run_interval = min(8760, max(1, schedule.run_interval // 60))
            schedule.save(update_fields=["run_interval"])

    operations = [
        migrations.AlterField(
            model_name="pipelineschedule",
            name="run_interval",
            field=models.IntegerField(
                default=1440,
                help_text="Number of minutes to wait between run of this pipeline.",
                validators=[
                    django.core.validators.MinValueValidator(
                        5, message="Interval must be at least 5 minutes."
                    ),
                    django.core.validators.MaxValueValidator(
                        43200, message="Interval must be at most 43200 minutes (i.e 30 days)."
                    ),
                ],
            ),
        ),
        migrations.RunPython(
            convert_hours_to_minutes,
            revert_convert_hours_to_minutes,
        ),
    ]
