# Generated by Django 5.2.11 on 2026-07-25 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0137_alter_pipelineschedule_run_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryHistoryDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_added', models.TextField(blank=True, null=True)),
                ('summary_removed', models.TextField(blank=True, null=True)),
                ('url_added', models.URLField(blank=True, null=True)),
                ('url_removed', models.URLField(blank=True, null=True)),
                ('added_aliases', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.advisoryalias')),
                ('added_impacted_packages', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.impactedpackage')),
                ('added_patches', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.patch')),
                ('added_references', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.advisoryreference')),
                ('added_severities', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.advisoryseverity')),
                ('added_weaknesses', models.ManyToManyField(blank=True, related_name='added_in_history', to='vulnerabilities.advisoryweakness')),
                ('advisory_after', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_diff', to='vulnerabilities.advisoryv2')),
                ('advisory_before', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_diff_before', to='vulnerabilities.advisoryv2')),
                ('removed_aliases', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.advisoryalias')),
                ('removed_impacted_packages', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.impactedpackage')),
                ('removed_patches', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.patch')),
                ('removed_references', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.advisoryreference')),
                ('removed_severities', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.advisoryseverity')),
                ('removed_weaknesses', models.ManyToManyField(blank=True, related_name='removed_in_history', to='vulnerabilities.advisoryweakness')),
            ],
        ),
    ]
