# Generated by Django 5.2.11 on 2026-06-30 08:15

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Concat


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0137_alter_pipelineschedule_run_interval"),
    ]

    def fix_malformed_cvss_severity(apps, schema_editor):
        AdvisorySeverity = apps.get_model("vulnerabilities", "AdvisorySeverity")

        AdvisorySeverity.objects.filter(
            scoring_system="cvssv3.1",
            scoring_elements__startswith="CVSS:3.0/",
        ).update(scoring_system="cvssv3")

        AdvisorySeverity.objects.filter(
            scoring_system="cvssv3",
            scoring_elements__isnull=False,
        ).exclude(
            scoring_elements="",
        ).exclude(
            scoring_elements__startswith="CVSS:3.0/",
        ).update(
            scoring_elements=Concat(
                Value("CVSS:3.0/"),
                "scoring_elements",
            )
        )

    operations = [
        migrations.RunPython(
            fix_malformed_cvss_severity,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
