# Generated by Django 5.2.11 on 2026-07-02 09:50

from django.db import migrations

from vulnerabilities.importer import AdvisoryDataV2
from vulnerabilities.importer import AffectedPackageV2
from vulnerabilities.importer import PatchData
from vulnerabilities.importer import ReferenceV2
from vulnerabilities.importer import VulnerabilitySeverity
from vulnerabilities.utils import compute_content_id_v2
from vulnerabilities.utils import normalize_list
from vulnerabilities.utils import purl_to_dict


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0138_fix_malformed_cvss_vector"),
    ]

    def cleanup_none_severity_string(apps, schema_editor):
        AdvisorySeverity = apps.get_model("vulnerabilities", "AdvisorySeverity")
        AdvisoryV2 = apps.get_model("vulnerabilities", "AdvisoryV2")
        batch = []
        batch_size = 5000

        advisory_ids = list(
            AdvisoryV2.objects.filter(severities__value="None")
            .distinct()
            .values_list("id", flat=True)
        )

        AdvisorySeverity.objects.filter(value="None").update(value="")

        for advisory in AdvisoryV2.objects.filter(id__in=advisory_ids).iterator(chunk_size=2000):
            advisory.unique_content_id = compute_content_id_v2(to_advisory_data(advisory))
            batch.append(advisory)

            if len(batch) >= batch_size:
                AdvisoryV2.objects.bulk_update(batch, ["unique_content_id"])
                batch.clear()

        if batch:
            AdvisoryV2.objects.bulk_update(batch, ["unique_content_id"])

    operations = [
        migrations.RunPython(
            cleanup_none_severity_string,
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def commit_patch_to_dict(patch):
    return {
        "vcs_url": patch.vcs_url,
        "commit_hash": patch.commit_hash,
        "patch_text": patch.patch_text,
        "patch_checksum": patch.patch_checksum,
    }


def to_affected_package_data(impact):
    """Return `AffectedPackageV2` data from the impact."""
    return AffectedPackageV2.from_dict(
        {
            "package": purl_to_dict(impact.base_purl),
            "affected_version_range": impact.affecting_vers,
            "fixed_version_range": impact.fixed_vers,
            "introduced_by_commit_patches": [
                commit_patch_to_dict(commit)
                for commit in impact.introduced_by_package_commit_patches.all()
            ],
            "fixed_by_commit_patches": [
                commit_patch_to_dict(commit)
                for commit in impact.fixed_by_package_commit_patches.all()
            ],
        }
    )


def to_patch_data(patch):
    """Return `PatchData` from the Patch."""

    return PatchData.from_dict(
        {
            "patch_url": patch.patch_url,
            "patch_text": patch.patch_text,
            "patch_checksum": patch.patch_checksum,
        }
    )


def to_reference_v2_data(ref):
    return ReferenceV2.from_dict(
        {
            "reference_id": ref.reference_id,
            "reference_type": ref.reference_type,
            "url": ref.url,
        }
    )


def to_vulnerability_severity_data(severity):
    return VulnerabilitySeverity.from_dict(
        {
            "system": severity.scoring_system,
            "value": severity.value,
            "scoring_elements": severity.scoring_elements,
            "published_at": severity.published_at,
            "url": severity.url,
        }
    )


def to_advisory_data(advisory):
    return AdvisoryDataV2(
        advisory_id=advisory.advisory_id,
        aliases=normalize_list([item.alias for item in advisory.aliases.all()]),
        summary=advisory.summary,
        affected_packages=normalize_list(
            [to_affected_package_data(impacted) for impacted in advisory.impacted_packages.all()]
        ),
        references=normalize_list([to_reference_v2_data(ref) for ref in advisory.references.all()]),
        patches=normalize_list([to_patch_data(patch) for patch in advisory.patches.all()]),
        date_published=advisory.date_published,
        weaknesses=normalize_list([weak.cwe_id for weak in advisory.weaknesses.all()]),
        severities=normalize_list(
            [to_vulnerability_severity_data(sev) for sev in advisory.severities.all()]
        ),
        url=advisory.url,
    )
