# Generated by Django 5.2.11 on 2026-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0139_cleanup_none_string_in_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisorytodo",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("MISSING_AFFECTED_PACKAGE", "Advisory is missing affected package"),
                    ("MISSING_FIXED_BY_PACKAGE", "Advisory is missing fixed-by package"),
                    (
                        "MISSING_AFFECTED_AND_FIXED_BY_PACKAGES",
                        "Advisory is missing both affected and fixed-by packages",
                    ),
                    ("MISSING_SUMMARY", "Advisory is missing summary"),
                    (
                        "CONFLICTING_FIXED_BY_PACKAGES",
                        "Advisories have conflicting fixed-by packages",
                    ),
                    (
                        "CONFLICTING_AFFECTED_PACKAGES",
                        "Advisories have conflicting affected packages",
                    ),
                    (
                        "CONFLICTING_AFFECTED_AND_FIXED_BY_PACKAGES",
                        "Advisories have conflicting affected and fixed-by packages",
                    ),
                    ("CONFLICTING_SEVERITY_SCORES", "Advisories have conflicting severity scores"),
                    ("CONFLICTING_WEAKNESSES", "Advisories have conflicting weaknesses"),
                ],
                db_index=True,
                help_text="Select the issue that needs to be addressed from the available options.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="advisorytodov2",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("MISSING_AFFECTED_PACKAGE", "Advisory is missing affected package"),
                    ("MISSING_FIXED_BY_PACKAGE", "Advisory is missing fixed-by package"),
                    (
                        "MISSING_AFFECTED_AND_FIXED_BY_PACKAGES",
                        "Advisory is missing both affected and fixed-by packages",
                    ),
                    ("MISSING_SUMMARY", "Advisory is missing summary"),
                    (
                        "CONFLICTING_FIXED_BY_PACKAGES",
                        "Advisories have conflicting fixed-by packages",
                    ),
                    (
                        "CONFLICTING_AFFECTED_PACKAGES",
                        "Advisories have conflicting affected packages",
                    ),
                    (
                        "CONFLICTING_AFFECTED_AND_FIXED_BY_PACKAGES",
                        "Advisories have conflicting affected and fixed-by packages",
                    ),
                    ("CONFLICTING_SEVERITY_SCORES", "Advisories have conflicting severity scores"),
                    ("CONFLICTING_WEAKNESSES", "Advisories have conflicting weaknesses"),
                ],
                db_index=True,
                help_text="Select the issue that needs to be addressed from the available options.",
                max_length=50,
            ),
        ),
    ]
