# Generated by Django 5.2.11 on 2026-08-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0141_advisorymitigations"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryv2",
            name="is_curation",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates whether this is a curation advisory.",
            ),
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="resolves_todos",
            field=models.ManyToManyField(
                help_text="A list of Advisory ToDos resolved by this advisory.",
                related_name="resolved_in_advisories",
                to="vulnerabilities.advisorytodov2",
            ),
        ),
    ]
