# Generated by Django 5.2.11 on 2026-07-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0138_advisoryhistorydiff'),
        ('vulnerabilities', '0141_advisorymitigations'),
    ]

    operations = [
    ]
