# Generated by Django 5.2.11 on 2026-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0142_advisoryv2_is_curation_advisoryv2_resolves_todos"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="impactedpackageaffecting",
            name="vulnerabili_impacte_1904b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="impactedpackagefixedby",
            name="vulnerabili_impacte_390971_idx",
        ),
        migrations.AlterField(
            model_name="impactedpackageaffecting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="impactedpackagefixedby",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pipelinerun",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
