# Generated by Django 5.2.11 on 2026-10-08 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vulnerabilities",
            "0143_remove_impactedpackageaffecting_vulnerabili_impacte_1904b9_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Curator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the curator.", max_length=100, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp indicating when this curator was added.",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advisoryv2",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                help_text="The curator who submitted this curation advisory.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curations",
                to="vulnerabilities.curator",
            ),
        ),
    ]
