# Generated by Django 5.2.11 on 2026-09-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vulnerabilities",
            "0143_remove_impactedpackageaffecting_vulnerabili_impacte_1904b9_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="advisoryv2",
            name="advisory_latest_by_avid_idx",
        ),
        migrations.RemoveIndex(
            model_name="advisoryv2",
            name="advisory_unfurled_idx",
        ),
    ]
